/// <reference types="npm:@types/react@18.3.1" />
import * as React from 'npm:react@18.3.1'
import {
  Body,
  Container,
  Head,
  Html,
  Preview,
  Section,
  Text,
} from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

const SITE_NAME = 'InfradarAI'
const SITE_URL = 'https://infradarai.com'
const PRIMARY = 'hsl(170, 55%, 63%)'
const FOREGROUND = '#0d1114'
const MUTED = '#55636a'

interface OutreachProps {
  subject?: string
  // Freeform, AI-drafted plain-text body (already personalised by the draft agent).
  body?: string
  // Optional UTM'd CTA link appended after the body.
  ctaUrl?: string
  ctaLabel?: string
}

/**
 * Renders an AI-drafted outbound message as a plain, low-key personal email.
 * Deliberately minimal chrome — outbound converts best when it reads like a
 * person wrote it, not a marketing blast. Plain-text fallback is generated by
 * the sender via react-email's plainText render.
 */
const OutreachEmail = ({ subject, body = '', ctaUrl, ctaLabel }: OutreachProps) => {
  const lines = body.split('\n').map((l) => l.trim())
  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>{subject || `A quick note from ${SITE_NAME}`}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section>
            {lines.map((line, i) =>
              line === '' ? (
                <Text key={i} style={spacer}>&nbsp;</Text>
              ) : (
                <Text key={i} style={text}>{line}</Text>
              )
            )}
          </Section>

          {ctaUrl ? (
            <Text style={text}>
              <a href={ctaUrl} style={link}>{ctaLabel || 'Take a look'}</a>
            </Text>
          ) : null}

          <Text style={footer}>
            {SITE_NAME} &middot;{' '}
            <a href={SITE_URL} style={link}>infradarai.com</a>
            {' '}&middot;{' '}
            <a href={`${SITE_URL}/unsubscribe`} style={link}>Unsubscribe</a>
            <br />
            You received this because your work involves global infrastructure projects.
            Reply &quot;stop&quot; or use the link above and we won&apos;t contact you again.
          </Text>
        </Container>
      </Body>
    </Html>
  )
}

export const template = {
  component: OutreachEmail,
  subject: (data: Record<string, any>) =>
    (data.subject && String(data.subject).trim()) || `A quick note from ${SITE_NAME}`,
  displayName: 'Outbound outreach (AI-drafted)',
  previewData: {
    subject: 'Pre-tender pipeline across 7 MDBs — for Actis',
    body:
      'Hi Nicolas,\n\nQuick one. I run InfraRadarAI — verified, source-linked infrastructure intelligence across all 7 MDBs plus 20+ procurement portals.\n\nFor a fund like Actis, the wedge is sourcing deals 6-18 months before they hit IJGlobal.\n\nOpen to a 10-min walkthrough this week?\n\n— Kinlo',
    ctaUrl: 'https://infradarai.com/?utm_source=outreach&utm_campaign=infra_pe',
    ctaLabel: 'Start a card-free trial',
  },
} satisfies TemplateEntry

const main = {
  backgroundColor: '#ffffff',
  fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif",
}
const container = { padding: '24px 28px', maxWidth: '560px' }
const text = { fontSize: '15px', color: FOREGROUND, lineHeight: '1.6', margin: '0 0 12px' }
const spacer = { fontSize: '8px', lineHeight: '8px', margin: 0 }
const footer = { fontSize: '12px', color: MUTED, margin: '28px 0 0', paddingTop: '16px', borderTop: '1px solid #e6e8ea', lineHeight: '1.5' }
const link = { color: PRIMARY, textDecoration: 'none' }
