// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List infrastructure projects",
  description: "List infrastructure projects tracked in InfraRadar. Supports optional filters for country, region, sector, and stage, plus a text query on project name/description. Returns id, name, country, region, sector, stage, value_usd, health_score, and last_updated.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text match against project name/description."),
    country: z.string().trim().optional().describe("ISO country name or code, e.g. 'Germany'."),
    region: z.string().trim().optional().describe("Region label used by InfraRadar, e.g. 'Europe'."),
    sector: z.string().trim().optional().describe("Sector, e.g. 'Energy', 'Transport'."),
    stage: z.string().trim().optional().describe("Project stage, e.g. 'planning', 'construction'."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const limit = input.limit ?? 25;
    let q = supabaseForUser(ctx).from("projects").select("id,name,country,region,sector,stage,value_usd,health_score,last_updated").order("last_updated", { ascending: false }).limit(limit);
    if (input.country) q = q.ilike("country", `%${input.country}%`);
    if (input.region) q = q.eq("region", input.region);
    if (input.sector) q = q.ilike("sector", `%${input.sector}%`);
    if (input.stage) q = q.ilike("stage", `%${input.stage}%`);
    if (input.query) q = q.or(`name.ilike.%${input.query}%,description.ilike.%${input.query}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project detail",
  description: "Fetch the full record for a single InfraRadar infrastructure project by id, including description, risks, funding sources, health signals, and political context.",
  inputSchema: {
    project_id: z2.string().uuid().describe("Project id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("projects").select("*").eq("id", project_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Project not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-alerts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_alerts_default = defineTool3({
  name: "list_alerts",
  title: "List recent alerts",
  description: "Return the most recent InfraRadar alerts (risk, tender, market, ESG signals). Optional filters for severity and category.",
  inputSchema: {
    severity: z3.enum(["low", "medium", "high", "critical"]).optional(),
    category: z3.string().trim().optional().describe("Alert category, e.g. 'risk', 'tender', 'market', 'esg'."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ severity, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("alerts").select("id,project_id,project_name,severity,category,message,source_url,origin,created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (severity) q = q.eq("severity", severity);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tracked-projects.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tracked_projects_default = defineTool4({
  name: "list_tracked_projects",
  title: "List my tracked projects",
  description: "Return the current user's tracked/watchlisted infrastructure projects with the associated notes. Uses row-level security so callers only see their own watchlist.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("tracked_projects").select("id,project_id,notes,created_at,projects(id,name,country,sector,stage,health_score)").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tracked: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yofglpxqpouqqhkidlkx";
var mcp_default = defineMcp({
  name: "infradarai-mcp",
  title: "InfraRadarAI",
  version: "0.1.0",
  instructions: "Read-only tools for the InfraRadarAI infrastructure intelligence platform. Use list_projects to discover global infrastructure projects (filter by country/region/sector/stage or free-text), get_project for the full record on a single project, list_alerts for recent risk/tender/market/ESG signals, and list_tracked_projects for the signed-in user's watchlist. All calls act as the authenticated user and respect row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, get_project_default, list_alerts_default, list_tracked_projects_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
